version: '3.8'

services:
  postgres:
    # build:
    #     context: .
    image: postgres:14
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Finiteloop123
      POSTGRES_DB: norm_db_00
    ports:
      - "5435:5432"    # Expose external port 5435, internally use 5432
    volumes:
      - mcm_db:/db_data   #remember to docker volume create mcm_db first
    networks:
      - mcm-network

  python-app:
    build:
      context: .   # Path to your Dockerfile and create_db.py
    container_name: python-db-init
    depends_on:
      - postgres   # Ensure PostgreSQL is up before running the Python script
    networks:
      - mcm-network
    volumes:
      - ..:/code
    stdin_open: true  # Keep stdin open so we can attach later
    tty: true         # Allocate a pseudo-TTY for interactive shell
    command: /bin/bash  # Start a bash shell

######
######   Remember to run docker network create mcm_network first
######

networks:
  mcm-network:
    external: true
    name: mcm_network
        

volumes:
  mcm_db:
